name: Add new issues to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: needs-triage
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/marcusolsson/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
