name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow:

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write # for actions/stale to close stale issues
      pull-requests: write # for actions/stale to close stale PRs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message:
            "This bot triages issues and PRs according to the following rules:
            - After 60d of inactivity, lifecycle/stale is applied.
            - After 30d of inactivity since lifecycle/stale was applied, lifecycle/rotten is applied and the issue is closed.
            You can:
            - Make a comment to remove the stale label and show your support. The 60 days reset.
            - If an issue has lifecycle/rotten and is closed, comment and ask maintainers if they'd be interested in reopening"

          stale-pr-message:
            "This bot triages issues and PRs according to the following rules:
            - After 60d of inactivity, lifecycle/stale is applied.
            - After 30d of inactivity since lifecycle/stale was applied, lifecycle/rotten is applied and the PR is closed.
            You can:
            - Make a comment to remove the stale label and show your support. The 60 days reset.
            - If a PR has lifecycle/rotten and is closed, comment and ask maintainers if they'd be interested in reopening."

          days-before-stale: 60
          days-before-close: 30
          stale-issue-label: "lifecycle/stale"
          stale-pr-label: "lifecycle/stale"
          exempt-issue-labels: "lifecycle/frozen"
          exempt-pr-labels: "lifecycle/frozen"
          close-issue-label: "lifecycle/rotten"
          close-pr-label: "lifecycle/rotten"
          exempt-issue-labels: "triage/confirmed"
